INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('ntruter42', 'Nicholas Truter', 'admin', 'password123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('emusk69', 'Elon Musk', 'waiter', 'tesla123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('jbezos007', 'Jeff Bezos', 'waiter', 'amazon123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('msuck404', 'Mark Zuckerberg', 'waiter', 'fakebook123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('bgates1', 'Bill Gates', 'waiter', 'microsoft123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('sjobs1337', 'Steve Jobs', 'waiter', 'apple123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('tcook100', 'Tim Cook', 'waiter', 'apple123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('eschmidt777', 'Eric Schmidt', 'waiter', 'google123', '0123456789101112');
INSERT INTO development.users (username, full_name, role, password, salt) VALUES ('spichai123', 'Sundar Pichai', 'waiter', 'google123', '0123456789101112');

INSERT INTO development.days (day_name) VALUES ('Monday');
INSERT INTO development.days (day_name) VALUES ('Tuesday');
INSERT INTO development.days (day_name) VALUES ('Wednesday');
INSERT INTO development.days (day_name) VALUES ('Thursday');
INSERT INTO development.days (day_name) VALUES ('Friday');
INSERT INTO development.days (day_name) VALUES ('Saturday');
INSERT INTO development.days (day_name) VALUES ('Sunday');

INSERT INTO development.assignments (user_id, day_id) VALUES (2, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (2, 2);
INSERT INTO development.assignments (user_id, day_id) VALUES (2, 3);
INSERT INTO development.assignments (user_id, day_id) VALUES (2, 4);
INSERT INTO development.assignments (user_id, day_id) VALUES (2, 5);
INSERT INTO development.assignments (user_id, day_id) VALUES (3, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (3, 5);
INSERT INTO development.assignments (user_id, day_id) VALUES (4, 7);
INSERT INTO development.assignments (user_id, day_id) VALUES (5, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (5, 3);
INSERT INTO development.assignments (user_id, day_id) VALUES (5, 5);
INSERT INTO development.assignments (user_id, day_id) VALUES (6, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (6, 2);
INSERT INTO development.assignments (user_id, day_id) VALUES (6, 3);
INSERT INTO development.assignments (user_id, day_id) VALUES (7, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (7, 2);
INSERT INTO development.assignments (user_id, day_id) VALUES (7, 3);
INSERT INTO development.assignments (user_id, day_id) VALUES (7, 4);
INSERT INTO development.assignments (user_id, day_id) VALUES (7, 6);
INSERT INTO development.assignments (user_id, day_id) VALUES (8, 1);
INSERT INTO development.assignments (user_id, day_id) VALUES (8, 3);
INSERT INTO development.assignments (user_id, day_id) VALUES (8, 5);
INSERT INTO development.assignments (user_id, day_id) VALUES (8, 7);